## ansible-playbook universal_java_upgrade.yml -i inventory/devfacets.inv -extra-vars "networx_1= networx_2= workflow_1= workflow_2="" --vault-password-file /home/<username>/.<username>
## need to run as <username> user.
# Required variables:
#   old_version = The old version of the installer (211)
#   version = The version number of the installer (231)
#   networx_1 = The number in the name of the service (9081 or 20081)
#   networx_2 = The number in the name of the service (9082 or 20082)
#   workflow_1 = The number in the name of the service (9083 or 20083)
#   workflow_2 = The number in the name of the service (9084 or 20084)
# Created by Devin St. Clair

 
---

- hosts: nwx_core
  user: <username>
  gather_facts: no
  become: no
  vars_files:
    - /home/<username>/automate/auto.yml
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore

  tasks:


# Copy Installers To Servers
  - name: Copy Installers
    win_copy:
      src: "{{ item }}"
      dest: C:\temp\
    with_items:
      - /opt/nas/facets_ansible/jdk-{{ version }}-windows-x64.exe

 
# Stop NWX Services  

  - name: Start NetworX_{{ networx_1 }} Service
    win_service:
      name: NetworX_{{ networx_1 }}
      state: stopped

  - name: Start NetworX_{{ networx_2 }} Service
    win_service:
      name: NetworX_{{ networx_2 }}
      state: stopped

  - name: Start Workflow_{{ workflow_1 }} Service
    win_service:
      name: Workflow_{{ workflow_1 }}
      state: stopped

  - name: Start  Workflow_{{ workflow_2 }} Service
    win_service:
      name: Workflow_{{ workflow_2 }}
      state: stopped


# Uninstall Old and Install New JDK and JRE

  - name: Uninstall Old JDK
    win_package:
      product_id: '{26A24AE4-039D-4CA4-87B4-2F64180{{ old_version }}F0}'
      state: absent

  - name: Uninstall Old JRE
    win_package:
      product_id: '{64A3A4F4-B792-11D6-A78A-00B0D0180{{ old_version }}}'
      state: absent

  - name: Install New JDK
    win_shell: |
      C:\temp\jdk-{{ version }}-windows-x64.exe /s ADDLOCAL="ToolsFeature,SourceFeature,PublicjreFeature" INSTALLDIR='C:\Program Files\Java\jdk' /INSTALLDIRPUBJRE='C:\Program Files\Java\jre'


# Start NWX Servers

  - name: Start NetworX_{{ networx_1 }} Service
    win_service:
      name: NetworX_{{ networx_1 }}
      state: started

  - name: Start NetworX_{{ networx_2 }} Service
    win_service:
      name: NetworX_{{ networx_2 }}
      state: started

  - name: Start Workflow_{{ workflow_1 }} Service
    win_service:
      name: Workflow_{{ workflow_1 }}
      state: started

  - name: Start  Workflow_{{ workflow_2 }} Service
    win_service:
      name: Workflow_{{ workflow_2 }}
      state: started